image: golang:alpine

cache:
  paths:
    - /go/src/
stages:
  - test
  - build
  - deploy

test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  before_script:
    - ./ci-prepare.sh
  script:
    - CGO_ENABLED=0 go test ./...

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  before_script:
    - ./ci-prepare.sh
  script:
    - ./ci-build.sh
  artifacts:
    paths:
      - '*.windows-*'
      - '*.linux-*'

deploy-nightly:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  image: docker:stable
  services:
    - name: docker:stable-dind
      command: [ "--experimental" ]
  before_script:
    - ./ci-prepare.sh
  script:
    - ./ci-deploy.sh nightly

deploy-latest:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  image: docker:stable
  services:
    - name: docker:stable-dind
      command: [ "--experimental" ]
  before_script:
    - ./ci-prepare.sh
  script:
    - ./ci-deploy.sh latest
