image: golang:alpine

cache:
  paths:
    - /go/src/
stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - ./ci-prepare.sh
  script:
    - CGO_ENABLED=0 go test ./...

build:
  stage: build
  only:
    - pushes
    - master
  before_script:
    - ./ci-prepare.sh
  script:
    - ./ci-build.sh
  artifacts:
    paths:
      - '*.windows-*'
      - '*.linux-*'

deploy-nightly:
  stage: deploy
  only:
    - develop
  image: docker:stable
  services:
    - name: docker:stable-dind
      command: [ "--experimental" ]
  before_script:
    - ./ci-prepare.sh
  script:
    - ./ci-deploy.sh nightly

deploy-latest:
  stage: deploy
  only:
    - master
  image: docker:stable
  services:
    - name: docker:stable-dind
      command: [ "--experimental" ]
  before_script:
    - ./ci-prepare.sh
  script:
    - ./ci-deploy.sh latest
