application:
  # base URL of front-end portal (to be sent to forwarders on 2FA or Captcha requests)
  base_url: http://localhost:9221
  # listen address for front-end
  portal_listener: 0.0.0.0:9221
  # listen address for Chrome remote debugger
  chrome_listener: 127.0.0.1:9222
carousell:
  # either this or `username` and `password` or both are required, entire Cookie header from https://carousell.sg
  cookie: _t2=..._t=...auth-session=...
  # either this or `cookie` or both are required, specify username and password for automatic session renewal (if Docker, make sure to run with env `INSTALL_CHROME=1`)
  username: username
  password: password
  # interval to ping Carousell to check connectivity
  ping_interval: 60
  # percentage of price to be considered low-ball in decimal notation
  low_ball: 0.7
message_templates: # message templates
  faq: |- # frequently answered questions (optional, leave empty if not required)
    FAQ:
    » Where do I normally deal?
    Anywhere

    » What payment methods do I accept?
    In order of preference: Google Pay, PayLah, PayNow, Cash, CarouPay, Bank Transfer

    » Why I might not have replied your message?
    Very likely you offered too low-ball of a price, please raise your offer
  initial: |- # new chat initial greeting
    Hello @{{NAME}}!

    Thanks for your interest in my item `{{ITEM}}`

    Do take a look at the FAQ sent above if you have any questions

    I will try to get back to you in person as soon as possible!
  not_available: |- # chat message on a listing that is sold, reserved or deleted
    Please note that this listing might not be available anymore as it was {{REASON}}.
  offered: |- # official offer using Carousell's offer button
    Thank you for your offer of ${{OFFER}}!
  possible_offer: |- # offer value detected from previously sent message
    It looks like you are making an offer of ${{OFFER}}.

    I will recommended to use Carousell's MAKE OFFER button for a faster response.
  lower_offer: |- # official offer value was decreased from possible offer, buyer being cheeky?
    WARNING: Offer was lowered!
  low_balled: |- # low-balled
    WARNING: Your offer is {{PERCENT}}% below listing price, it's pretty low!
  contact: |- # contact details reply for contact command
    My contact details:
      Mobile: +6591234567
      WhatsApp: https://api.whatsapp.com/send?phone=6591234567
      Telegram: https://t.me/telegram_username
  reminder: |- # reminder
    REMINDER: We are dealing this in {{HOURS}} hour(s)!
reminders: # list of hours to set reminders for on every deal (optional, leave empty if none)
  - 1
  - 4
  - 24
# prefix to use for the app to detect as a command
command_prefix: "."
# number of days to keep items in state after last activity
state_prune: 14
forwarders: # list of forwarders (optional, `[]` if none)
  - type: telegram
    token: '1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZabcde1234' # bot token
    chat_id: 87654321 # chat id
    message_templates:
      standard: |- # standard message
        *Carousell Chat/Offer*
        [{{NAME}} - {{ITEM}}](https://www.carousell.sg/inbox/{{ID}})
        ${{OFFER}}
        {{FLAGS}}
      reminder: |- # reminder message
        *Carousell Deal Reminder*
        [{{ITEM}}](https://www.carousell.sg/inbox/{{ID}})
        Deal ${{OFFER}} in {{HOURS}} hour(s)!
  - type: discord
    webhook_url: 'https://discord.com/api/webhooks/012345678910111213/lrennsXdocFAKEdOWAkpWEBHOOKMrMMcXa_FcmCURLUMNU_STsnbKVTRirmvLccmvkpA' # webhook url
    message_templates:
      standard: |- # standard message
        **Carousell Chat/Offer**
        [{{NAME}} - {{ITEM}}](https://www.carousell.sg/inbox/{{ID}})
        ${{OFFER}}
        {{FLAGS}}
      reminder: |- # reminder message
        **Carousell Reminder**
        [{{ITEM}}](https://www.carousell.sg/inbox/{{ID}})
        Deal ${{OFFER}} in {{HOURS}} hour(s)!
  - type: slack
    webhook_url: 'https://hooks.slack.com/services/T1234GN5678/B1FAKEZNRCM/fPoWEBHOOK2Yyn3oURLOjW4J' # webhook url
    message_templates:
      standard: |- # standard message
        *Carousell Chat/Offer*
        <https://www.carousell.sg/inbox/{{ID}}|{{NAME}} - {{ITEM}}>
        ${{OFFER}}
        {{FLAGS}}
      reminder: |- # reminder message
        *Carousell Reminder*
        <https://www.carousell.sg/inbox/{{ID}}|{{ITEM}}>
        Deal ${{OFFER}} in {{HOURS}} hour(s)!
